'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=5.153.14.228,779;Initial Catalog=chrisbarton_grg10;Persist Security I"& _ 
            "nfo=True;User ID=chrisbarton_chris;Password=G@rf0rt#")>  _
        Public ReadOnly Property chrisbarton_grg10ConnectionString() As String
            Get
                Return CType(Me("chrisbarton_grg10ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("D:\RAMBLERS\WEBSITE")>  _
        Public Property defaultLocalPath() As String
            Get
                Return CType(Me("defaultLocalPath"),String)
            End Get
            Set
                Me("defaultLocalPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1200")>  _
        Public Property winx() As Integer
            Get
                Return CType(Me("winx"),Integer)
            End Get
            Set
                Me("winx") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("800")>  _
        Public Property winy() As Integer
            Get
                Return CType(Me("winy"),Integer)
            End Get
            Set
                Me("winy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ftp.glenrothesramblers.co.uk")>  _
        Public Property ftpurl() As String
            Get
                Return CType(Me("ftpurl"),String)
            End Get
            Set
                Me("ftpurl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("chrisbarton")>  _
        Public Property ftpuser() As String
            Get
                Return CType(Me("ftpuser"),String)
            End Get
            Set
                Me("ftpuser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G@rf0rt#")>  _
        Public Property ftppword() As String
            Get
                Return CType(Me("ftppword"),String)
            End Get
            Set
                Me("ftppword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:")>  _
        Public Property defaultfolder() As String
            Get
                Return CType(Me("defaultfolder"),String)
            End Get
            Set
                Me("defaultfolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<!DOCTYPE html>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<html xmlns=""http://www.w3.org/1999/xhtml"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<head>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    <title>"& _ 
            "DATABASE MANAGER DOCUMENTATION</title>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    <style>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        body {"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    font-fa"& _ 
            "mily: Calibri, Arial, Sans-serif;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    font-size: 20px;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    font-weight: 500;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
            "    padding: 0 0 0 0;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    background-color: white;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        h1 {"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    font-f"& _ 
            "amily: Calibri, Arial, Sans-serif;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    font-size: 26px;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    font-weight: bold;"& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    color: black;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"   }"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"h2 {"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    font-family: Calibri, Arial, Sans-serif;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    font-size: 22px;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    font-weight: bold;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    color: blue;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"h3 {"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    fo"& _ 
            "nt-family: Calibri, Arial, Sans-serif;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    font-size: 22px;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    font-weight: b"& _ 
            "old;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    color: navy;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"text-decoration: underline;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"a {"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    font-size: 20p"& _ 
            "x;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    font-weight: bold;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    text-decoration: none;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    color: blue;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&" "& _ 
            "   a:hover {"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        color: magenta;"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    }"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    </style>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</head>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<body>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<a "& _ 
            "name=""index""></a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h1>HELP TOPICS</h1>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    <ul>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        <li><a href=""#new"">St"& _ 
            "arting with a new programme period</a></li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        <li><a href=""#prog"">Constru"& _ 
            "cting the programme</a></li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        <li><a href=""#gridref"">Finding Grid Refere"& _ 
            "nces</a></li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li><a href=""#walks"">Managing the Walks and Leaders Tables</a><"& _ 
            "/li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li><a href=""#pub"">Publishing the Programme</a></li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li><a href=""#ev"& _ 
            "ents"">Managing the Programme after Publication</a></li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li><a href=""#ajp"">Up"& _ 
            "loading New AJP PDF files</a></li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li><a href=""#maps"">Managing OS Route Maps"& _ 
            "</a></li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li><a href=""#photos"">Managing the Photo Albums</a></li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li><a "& _ 
            "href=""#contacts"">Managing the Group Contacts</a></li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        <li><a href=""#err"& _ 
            "ors"">Database Error Messages </a></li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"<li><a href=""#appendix"">Appendix - Dat"& _ 
            "a Table reference </a></li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    </ul>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<a name=""new""></a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    <h2>Starting wit"& _ 
            "h a new programme period</h2>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"The controls for this are in the first panel on t"& _ 
            "he [Tools] page. This will delete the previous Programme table! Start by selecti"& _ 
            "ng a date from the calendar, then click [Select this date]. This should be the f"& _ 
            "irst walk date of the period, so usually the first Thursday, Saturday or Sunday."& _ 
            " Then click [Make New Programme]. The table is initiated with Strollers Walks an"& _ 
            "d Leaders set for each Thursday. Weekend walks are set for alternate Saturdays a"& _ 
            "nd Sundays with Walks and Leaders set to ""- none chosen"" <br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"View the Progra"& _ 
            "mme on the [Programme Design] page, and check that the dates are correct. Click "& _ 
            "[Include Strollers] to show all the dates. Some dates may not be required, parti"& _ 
            "cularly in the Winter programme, with the Xmas and NY holidays. Select any unwan"& _ 
            "ted dates, one at a time, and click [Delete Item] to remove them. When the list "& _ 
            "of dates is correct click [Save Changes]. Note that no changes are made to the o"& _ 
            "nline database, from any input form until a SAVE button is pressed. At any time,"& _ 
            " clicking an UNDO button or the [Reload Database] button abandons any changes ma"& _ 
            "de since the last SAVE.(Except for limited circumstances as described)<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
            " <a name=""prog""></a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h2>Constructing the programme</h2>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"This uses the first t"& _ 
            "wo pages - [Programme Design] and [Programme Details]. The design page shows all"& _ 
            " the dates, but limited information. The top of the page has a calendar control "& _ 
            "for the date and two list boxes for walks and leaders from database tables. Chan"& _ 
            "ging the date or selecting a walk or leader from the lists brings up confirm dia"& _ 
            "log. After making changes, they can be viewed in detail on the second page which"& _ 
            " only shows one programme item at a time. The walk and leader details are taken "& _ 
            "from the database but can be adjusted if needed on the details page. The arrow b"& _ 
            "uttons at the top of the details page can be used to scroll through the list of "& _ 
            "programme items. Stroller walks have a fixed output to the AJP and Ramblers Walk"& _ 
            " Finder and can't be edited (other than deleting).<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"If the item is a non-s"& _ 
            "tandard entry, (such as an AGM, Social event or Group Weekend) click the [EVENT]"& _ 
            " link on the design page. That sets the value of the Grade field to ""EVENT"" whic"& _ 
            "h removes everything from the output files except the item name and description."& _ 
            " The Leader entry for an event should be the contact details.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"If the Walk"& _ 
            " entry is new walk, not in the database, then click the [Add New Walk to list] b"& _ 
            "utton on the design page. This opens a ""New Walk"" details form. Fill in all the "& _ 
            "details then click the Save button. This saves the new walk to the database, the"& _ 
            "n returns to the ""Change Walk"" dialog for the selected date.<br /> Alternatively"& _ 
            ", a new walk can be added from the [Walks] page, saved, then selected from the l"& _ 
            "ist. Note that the bold items on the form are required for all the output files "& _ 
            "(AJP, our Website and Ramblers website). The ""Nearest Town"" field is required to"& _ 
            " index the walks table on our website."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"If an extra item is required in the prog"& _ 
            "ramme, click the [Add New Date] button on the design page. Save the date then ad"& _ 
            "d walk and leader details on the design page.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"The [Draft] page shows a te"& _ 
            "xt file containing all the important information from the Programme table. The t"& _ 
            "ext can be copied and pasted into a document or an email. The Draft Programme ca"& _ 
            "n also be viewed online (with member's login) at <a href=""http://glenrothesrambl"& _ 
            "ers.co.uk/Private/Pages/DraftProgramme.aspx"">Draft Programme</a><br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<a nam"& _ 
            "e=""gridref""></a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h2>Finding Grid References</h2>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"An OS map page can be opened"& _ 
            " by clicking [OS Gridref Finder] or by one of the links on the ""New Walk"" forms."& _ 
            " This has a draggable pin, which can also be moved by clicking a place on the ma"& _ 
            "p. The grid reference, accurate to about 50m can be read in the box, as can the "& _ 
            "GPS coordinates. These readings can be copied and pasted using Ctrl-C and Ctrl-V"& _ 
            ". The map starts in Glenrothes, but there are a selection of links to alternativ"& _ 
            "e towns in S Scotland in the page header. Once a walk has been saved to the data"& _ 
            "base, a map with the starting grid reference marked can be shown by clicking the"& _ 
            " [Show ...] links on the details page or the [Walks] page.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<a name=""wal"& _ 
            "ks"" ></a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h2>Managing the Walks and Leaders Tables</h2>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"The [Walks] page has "& _ 
            "a list of all the walks in the database below with the details shown above. Walk"& _ 
            "s can be deleted, or new walks added from the menu. Changes made to details, del"& _ 
            "eted walks or new walks are transferred to the database when the [Save Changes] "& _ 
            "button is pressed. Walks are automatically hidden from the Members Walk Finder t"& _ 
            "able on the website when they are selected for the Programme. They can be hidden"& _ 
            "/unhidden manually. The walks table also shows the date and leader from when the"& _ 
            " walk was last published. This is set automatically when the programme is publis"& _ 
            "hed.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"The [Leaders] page is self-explanatory. Note that the Strollers Lead"& _ 
            "ers must always have the index number zero.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<a name=""pub""></a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h2>Pub"& _ 
            "lishing the Programme</h2>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"The Publication module is on the right of the [Tools"& _ 
            "] page."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"First click [Pre-publication check]. This checks that the individual da"& _ 
            "te items in the Programme can be published. All valid entries (not including ""- "& _ 
            "none chosen"") are checked for transfer to the Final Programme table. A summary o"& _ 
            "f the results is shown in the adjacent text box. If there are any database error"& _ 
            "s, a dialog box will show at that item describing the error."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Then click [Publis"& _ 
            "h Current Programme]. Firstly the Walks table is ammended to show the dates and "& _ 
            "leaders for the walks in the programme, then the Programme is copied to the Fina"& _ 
            "l Programme table."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&" If all dates have published without error, then go to the ["& _ 
            "Final Programme] page and check the results. If they are correct then click [Sav"& _ 
            "e Changes] to transfer the table to the online database. The programme is VISIBL"& _ 
            "E IMMEDIATELY on the Group Programme page of the website.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Publication gen"& _ 
            "erates three online files:<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ul><li>Website Group Walks page content - thi"& _ 
            "s is automatic. Walks are hidden 2 days after the current date.</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Area J"& _ 
            "oint Programme input. Click [AJP mail-merge] on main menu to open a dialog which"& _ 
            " explains how to transfer the output to Word Mail-merge documents, driven by 3 t"& _ 
            "ables for Weekend walks, Strollers walks and Events.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Spreads"& _ 
            "heet output to transfer walks to the Ramblers Walk Finder. <br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Click [Ramble"& _ 
            "rs Walk Finder] in the main menu. A page opens showing the procedure for constru"& _ 
            "cting a text-based spreadsheet. This is the format used to input multiple walks "& _ 
            "to the Ramblers website. Save the file then go to:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<a href=""http://www.ramblers"& _ 
            ".org.uk/group-walks-and-events-manager.aspx"">Group Walks and Events Manager</a>."& _ 
            " This requires a ""Group Walks Coordinator"" login. Then follow the instructions f"& _ 
            "or ""Uploading walks using a spreadsheet"" to upload the saved file and publish it"& _ 
            ", if the upload is successful.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</li></ul>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"When a Programme period expire"& _ 
            "s, after the date of its last walk, it can be deleted. Select the relevant perio"& _ 
            "d in the list box then click [Delete Selected Period]. Check in the [Final Progr"& _ 
            "amme] page that the correct period has been deleted then click [Save Changes] to"& _ 
            " confirm deletion. A message box reminder for this will be shown when opening th"& _ 
            "e page, if there is a redundant period.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<a name=""events"" ></a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h2>Manag"& _ 
            "ing the Programme after Publication</h2>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"The ""Final_Programme"" table contains d"& _ 
            "etails of the Walks Programme plus Social events, AGM, weekend etc. Walks and Ev"& _ 
            "ents are displayed on the Group Walks page and events are also displayed on the "& _ 
            "Group Info page. Like the walks, events are hidden the day after their date. One"& _ 
            " special event is the ""Stop Press"" which, if present, is displayed on a red bann"& _ 
            "er at the top of the home page. The Programme is managed by the [Group Programme"& _ 
            "] page. Click [Stop Press] on the main menu to put an item on the Home Page ie c"& _ 
            "hanges to walks. Only the date and description will be shown as ""Stop Press"".<br"& _ 
            " />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Programme items can be deleted or ammended on the [Group Programme] page. T"& _ 
            "here is a form for major alterations, such as a complete change to walk or leade"& _ 
            "r, or adding a new item by clicking the [Add or change programme item] button."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
            "The ""Description"" entry for any programme item can include simple formatting: [B"& _ 
            "] bold, [I] italic, and [U] underline. Select the section and click the relevant"& _ 
            " button, to add HTML tags to the text eg &lt;b&gt;some text&lt;/b&gt; for bold. "& _ 
            "Pressing the ENTER key adds an HTML line break (&lt;br /&gt;). "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<a name=""ajp"" >"& _ 
            "</a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h2>Uploading New AJP PDF files</h2>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"The website ""Area Walks"" page has de"& _ 
            "tails about the other groups in the area, and information about attending walks."& _ 
            " It has a link to the Ramblers Website ""Find a walk"" page with our area selected"& _ 
            ". This is updated for all groups using the method described above for our group,"& _ 
            " and is maintained and kept current by Ramblers. Our Area Joint Programme is ava"& _ 
            "ilable online as a PDF file to read or download, and all groups get a copy when "& _ 
            "published biannually. Current versions of both Winter and Summer programes are l"& _ 
            "inked to the Area Walks page. When a new AJP is published, go to the [Tools] pag"& _ 
            "e, [NEW AREA JOINT PROGRAMME] panel. Select Summer or Winter then click [Get AJP"& _ 
            " pdf file] to find the file. If the correct file is displayed, clicking [Upload "& _ 
            "AJP ..] will replace the previous file on the server with the new one. Check it "& _ 
            "by clicking the appropriate link on the Area Walks page."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<a name=""maps"" ></a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
            "<h2>Managing OS Route Maps</h2>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"This is done on the [Maps Manager] page. The ta"& _ 
            "ble on the left has the list of Walks with the associated file name if there is "& _ 
            "a route map. Select the required walk, then maps can be deleted or new maps adde"& _ 
            "d by clicking [Delete Map] or [Add New Map]. The latter brings up a File Open di"& _ 
            "alog box. Select the map on the local computer. If correct click [Save] to confi"& _ 
            "rm. The map file will be uploaded and the Walk record updated. Route maps on the"& _ 
            " server can be shown in a browser window by clicking [Show Route Map]. If file a"& _ 
            "ssociations have been deleted there will be redundant files on the server. Click"& _ 
            " [Find maps not being used] to find and [Delete these maps] to remove them."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<"& _ 
            "a name=""photos"" ></a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h2>Managing the Photo Albums</h2>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Photo files are store"& _ 
            "d on the website in yearly folders (There is an old photos folder, 2008-2010 ). "& _ 
            "A new folder is automatically created for the New Year the first time a file is "& _ 
            "uploaded after 1st January. The photos are displayed for the past 12 months, but"& _ 
            " any year can be displayed by clicking the year links on the right of the page.<"& _ 
            "br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"This is all managed by the [Photos] page. A table on the page shows the d"& _ 
            "etails. Captions can be altered and items can be deleted. If an item is deleted,"& _ 
            " the actual file will be deleted from the server, as well as the database refere"& _ 
            "nce. So clicking [Delete] cannot be undone in this case.<br /> "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Uploading photo"& _ 
            "s: any photos to be uploaded should have had their file size optimised for the w"& _ 
            "eb. Any image editing program will do this. The ideal file size generates an ima"& _ 
            "ge 700 pixels wide, which is the width displayed on the web page. This can be se"& _ 
            "t in most photo editors. Uploading raw images taken with a modern camera or phon"& _ 
            "e will slow the website down significantly! (A 10 megapixel camera generates fil"& _ 
            "es 64 x the size of a 700 pixel wide web picture)<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"To add a photo to the c"& _ 
            "urrent year's album, click [Upload New Photos]. Clicking [Get Photo] opens a fil"& _ 
            "e dialog. Select the (optimised) file and it is displayed in a box 700 pixels wi"& _ 
            "de. If only a fraction of the photo is displayed, it is not suitable for a web p"& _ 
            "age! Add a caption in the text box and adjust the date if needed. Then click [Up"& _ 
            "load Photo]. An entry is made in the database and the file is uploaded to the we"& _ 
            "b server. This can be repeated until [Finished] if there are more photos. Then c"& _ 
            "heck the results at "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<a href=""http://glenrothesramblers.co.uk/Pages/Photoalbum."& _ 
            "aspx"">Photos Page</a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<a name=""contacts"" ></a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h2>Managing the Group Contacts"& _ 
            "</h2>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Go to the [Group Contacts] page. The table shown drives the website ""Cont"& _ 
            "acts"" page. Details are shown below. A contact can be edited or deleted and a ne"& _ 
            "w contact can be added with [Add New]. If a photo is required for a contact it c"& _ 
            "an be uploaded by clicking [Get Photo] then [Upload and Save Changes]. Any photo"& _ 
            "s should be optimised for a webpage as previously described. Ideally they should"& _ 
            " be 150 pixels wide. The email address will be changed to a clickable link on th"& _ 
            "e page. Clicking [Delete] will remove the photo from the server and cannot be un"& _ 
            "done."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<a name=""errors""></a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h2>Database Error Messages</h2>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Our website is h"& _ 
            "osted on a shared server, which is the only affordable option for a Ramblers gro"& _ 
            "up. The commonest errors that occur are conflict errors when the server is busy."& _ 
            " Usually trying again after a break is all that is required. More persistant err"& _ 
            "ors should be copied and emailed to the management at <a href= ""mailto:chrisandb"& _ 
            "etty@glenrothesramblers.co.uk"">Chris Barton</a>, as should any suggestions about"& _ 
            " improving this help file.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<a name=""appendix""></a>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h1>Appendix - Data T"& _ 
            "ables</h1>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h3>Programme Table</h3>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Function:</b> Design of 6 monthly walki"& _ 
            "ng programme.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Maintenance:</b> New table constructed programmatically "& _ 
            "from [Tools] page. Editing by [Programme Design] and [..Detail] pages.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b"& _ 
            ">Data Fields:</b>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ul>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Date / 6 month period </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Walk / Description"& _ 
            " *  </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Grade / Ascent / Distance / Time *  </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Meet time / Start "& _ 
            "time * </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Start place / OS map / Grid reference *  </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Child / Do"& _ 
            "g friendly *  </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Leader / Phone / Email # </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ul>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Fields marked (*"& _ 
            ") derived from Walks table, marked (#) derived from Leaders table."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h3>Final Pr"& _ 
            "ogramme Table</h3>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Function:</b> To display the walking programme on the web"& _ 
            "site and produce output for the AJP and Ramblers Walk Finder page.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Mai"& _ 
            "ntenance:</b> Each 6 month period generated at publication from the Programme ta"& _ 
            "ble. Edited by the [Final Programme] page.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Data Fields: </b>The same a"& _ 
            "s Programme table."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h3>Walks Table (called ALLWALKS)</h3>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Function: </b>To "& _ 
            "maintain a list of group walks and generate new walks produced by leaders.<br />"& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Maintenance: </b>By [Walks] page and [Add New Walk] form. <br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Data F"& _ 
            "ields: </b>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ul>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Walk / Description *  </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Grade / Ascent / Distanc"& _ 
            "e / Time *  </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Meet time / Start time * </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Start place / OS map "& _ 
            "/ Grid reference *  </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Child / Dog friendly *  </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Nearest Town ("& _ 
            "for indexing)</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Route Map</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Hide / unhide (to make walk invisibl"& _ 
            "e to leaders when selected)</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Last Leader / Last Date #</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ul>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Fie"& _ 
            "lds marked (*) are shared with Programme table, history items marked (#) are gen"& _ 
            "erated from Programme table at publication."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h3>Leaders Table</h3>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Function"& _ 
            ": </b>To maintain a list of walk leaders.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Maintenance: </b>By [Leaders"& _ 
            "] page.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Data Fields:</b>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ul>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Leader's displayed name </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li"& _ 
            ">Phone  </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Email</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ul>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h3>Photoalbum Table</h3>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Function: </"& _ 
            "b>Photos taken on walks, indexed by year and displated for last 12 months.<br />"& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Maintenance: </b>By [Photos] page and [Upload photo] form.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Data F"& _ 
            "ields:</b>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ul>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Date taken</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>File name (always a jpeg file) </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Folder name (usually a year eg ""2015"")  </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Caption</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ul>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<h3"& _ 
            ">Group Contacts Table</h3>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Function: </b>Maintain the list of contacts on th"& _ 
            "e website Contacts page.<br />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Maintenance: </b>By [Group Contacts] page.<br"& _ 
            " />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<b>Data Fields:</b>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ul>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Name</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Designation </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Phone "& _ 
            "number  </li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Email</li>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<li>Photo (optional)</li></ul>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</body> "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</html>"& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property helpSetting() As String
            Get
                Return CType(Me("helpSetting"),String)
            End Get
            Set
                Me("helpSetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("All are welcome to join this 4-6 mile walk, see details on the first page of this"& _ 
            " programme.")>  _
        Public Property strollerAJP() As String
            Get
                Return CType(Me("strollerAJP"),String)
            End Get
            Set
                Me("strollerAJP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fswiss\fprq2\fc"& _ 
            "harset0 Calibri;}{\f1\fnil\fcharset0 Calibri;}}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"{\*\generator Riched20 10.0.171"& _ 
            "34}\viewkind4\uc1 "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\pard\widctlpar\ul\f0\fs24 Ramblers Walk Finder spreadsheet "& _ 
            "fields\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\ulnone Italic fields (*) - not in our database, bold - calculated f"& _ 
            "rom database\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Date\tab\tab\tab\tab\tab as dd/mm/yyy\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Title\tab\tab"& _ 
            "\tab\tab\tab walk name\tab\tab\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Description\tab\tab\tab\tab description\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\i Linear or Circular*\tab\tab\tab\b circular or linear\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\b0\i0 Starting gr"& _ 
            "idref\tab\tab\tab as NN123456\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Starting location details\tab\tab Start Place"& _ 
            "\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\i Show exact starting point?*\tab\tab yes\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\i0 Start time\tab\tab\tab"& _ 
            "\tab as hh:mm\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\i Meeting gridref*\tab\tab\tab\b NO286008(LCCP) or NO269009("& _ 
            "StC)\b0\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Meeting location details*\tab\tab\b Lomond Centre CP or St Columbas"& _ 
            " Church CP\b0\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Show exact meeting point?*\tab\tab yes\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\i0 Meeting time\"& _ 
            "tab\tab\tab\tab as hh:mm\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\i Restriction*\tab\tab\tab\tab Public\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Diffic"& _ 
            "ulty*\tab\tab\tab\tab\b Easy Leisurely Moderate Strenuous\b0\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\i0 Local walk"& _ 
            " grade\tab\tab\tab A - D\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Distance miles\tab\tab\tab distance\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Contact d"& _ 
            "isplay name\tab\tab\tab leader name\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Contact email\tab\tab\tab\tab email\par"& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Contact telephone 1\tab\tab\tab phone\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\i Is walk leader?*\tab\tab\tab yes"& _ 
            "\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\i0 Ascent feet\tab\tab\tab\tab ascent\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Child friendly?\tab\tab\tab\ta"& _ 
            "b\b Yes or leave blank\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\pard\widctlpar\sa200\sl276\slmult1\b0 Dog friendl"& _ 
            "y?\tab\tab\tab\tab\b Yes or leave blank\b0\fs22\tab\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"\i Linear or circular i"& _ 
            "s derived from walk names.\line Meeting point according to whether Strollers or "& _ 
            "W/e walks.\line Difficulty is calculated from A - D values.\tab\i0\f1\lang9\par"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"}")>  _
        Public Property wfrtf() As String
            Get
                Return CType(Me("wfrtf"),String)
            End Get
            Set
                Me("wfrtf") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/httpdocs/")>  _
        Public Property basedir() As String
            Get
                Return CType(Me("basedir"),String)
            End Get
            Set
                Me("basedir") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Programme_Designer.My.MySettings
            Get
                Return Global.Programme_Designer.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
